//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.2046.0.
// 
namespace Potter.ApiExtraction.Core.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    [System.Xml.Serialization.XmlRootAttribute("Api", Namespace="http://schemas.danielrpotter.com/api/configuration/2017", IsNullable=false)]
    public partial class ApiConfiguration {
        
        private AssemblyConfiguration[] assembliesField;
        
        private NameConfiguration namesField;
        
        private GroupConfiguration[] groupsField;
        
        private bool simplifyNamespacesField;
        
        public ApiConfiguration() {
            this.simplifyNamespacesField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Assembly", IsNullable=false)]
        public AssemblyConfiguration[] Assemblies {
            get {
                return this.assembliesField;
            }
            set {
                this.assembliesField = value;
            }
        }
        
        /// <remarks/>
        public NameConfiguration Names {
            get {
                return this.namesField;
            }
            set {
                this.namesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Group", IsNullable=false)]
        public GroupConfiguration[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool SimplifyNamespaces {
            get {
                return this.simplifyNamespacesField;
            }
            set {
                this.simplifyNamespacesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public partial class AssemblyConfiguration {
        
        private string nameField;
        
        private string locationField;
        
        private bool loadField;
        
        public AssemblyConfiguration() {
            this.loadField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Load {
            get {
                return this.loadField;
            }
            set {
                this.loadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public partial class TypeConfiguration {
        
        private MemberSelector[] itemsField;
        
        private TypeMode modeField;
        
        private bool includeObsoleteField;
        
        public TypeConfiguration() {
            this.modeField = TypeMode.Blacklist;
            this.includeObsoleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Namespace", typeof(NamespaceSelector))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(TypeSelector))]
        public MemberSelector[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TypeMode.Blacklist)]
        public TypeMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IncludeObsolete {
            get {
                return this.includeObsoleteField;
            }
            set {
                this.includeObsoleteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public partial class NamespaceSelector : MemberSelector {
        
        private TypeSelector[] typesField;
        
        private bool recursiveField;
        
        public NamespaceSelector() {
            this.recursiveField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Type", IsNullable=false)]
        public TypeSelector[] Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Recursive {
            get {
                return this.recursiveField;
            }
            set {
                this.recursiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public partial class TypeSelector : MemberSelector {
        
        private UnionType[] unionTypeField;
        
        private string factoryNameField;
        
        private string managerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnionType")]
        public UnionType[] UnionType {
            get {
                return this.unionTypeField;
            }
            set {
                this.unionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FactoryName {
            get {
                return this.factoryNameField;
            }
            set {
                this.factoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ManagerName {
            get {
                return this.managerNameField;
            }
            set {
                this.managerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public partial class UnionType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeSelector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NamespaceSelector))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public abstract partial class MemberSelector {
        
        private string nameField;
        
        private string newNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewName {
            get {
                return this.newNameField;
            }
            set {
                this.newNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public enum TypeMode {
        
        /// <remarks/>
        Whitelist,
        
        /// <remarks/>
        Blacklist,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public partial class GroupConfiguration {
        
        private TypeConfiguration typesField;
        
        private string nameField;
        
        /// <remarks/>
        public TypeConfiguration Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/configuration/2017")]
    public partial class NameConfiguration {
        
        private MemberSelector[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Namespace", typeof(NamespaceSelector))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(TypeSelector))]
        public MemberSelector[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
