//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
[System.Xml.Serialization.XmlRootAttribute("Api", Namespace="http://schemas.danielrpotter.com/api/2017", IsNullable=false)]
public partial class ApiElement {
    
    private AssemblyElement assemblyField;
    
    private TypeSelectorElementBase[] itemsField;
    
    /// <remarks/>
    public AssemblyElement Assembly {
        get {
            return this.assemblyField;
        }
        set {
            this.assemblyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Add", typeof(AddTypeRefinableSelectorElement))]
    [System.Xml.Serialization.XmlElementAttribute("Clear", typeof(ClearTypeSelectorElement))]
    [System.Xml.Serialization.XmlElementAttribute("Remove", typeof(RemoveTypeRefinableSelectorElement))]
    public TypeSelectorElementBase[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public partial class AssemblyElement {
    
    private string nameField;
    
    private string locationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeFilterSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveTypeSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveTypeRefinableSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddTypeSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddTypeRefinableSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ClearTypeSelectorElement))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public abstract partial class TypeSelectorElementBase {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveTypeSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveTypeRefinableSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddTypeSelectorElement))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddTypeRefinableSelectorElement))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public abstract partial class TypeFilterSelectorElement : TypeSelectorElementBase {
    
    private bool abstractClassesField;
    
    private bool abstractClassesFieldSpecified;
    
    private bool interfacesField;
    
    private bool interfacesFieldSpecified;
    
    private string namespaceField;
    
    private string typeNameField;
    
    private string fullNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AbstractClasses {
        get {
            return this.abstractClassesField;
        }
        set {
            this.abstractClassesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AbstractClassesSpecified {
        get {
            return this.abstractClassesFieldSpecified;
        }
        set {
            this.abstractClassesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Interfaces {
        get {
            return this.interfacesField;
        }
        set {
            this.interfacesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InterfacesSpecified {
        get {
            return this.interfacesFieldSpecified;
        }
        set {
            this.interfacesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveTypeRefinableSelectorElement))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public partial class RemoveTypeSelectorElement : TypeFilterSelectorElement {
    
    private bool obsoleteField;
    
    private bool obsoleteFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Obsolete {
        get {
            return this.obsoleteField;
        }
        set {
            this.obsoleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ObsoleteSpecified {
        get {
            return this.obsoleteFieldSpecified;
        }
        set {
            this.obsoleteFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public partial class RemoveTypeRefinableSelectorElement : RemoveTypeSelectorElement {
    
    private AddTypeSelectorElement[] addField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Add")]
    public AddTypeSelectorElement[] Add {
        get {
            return this.addField;
        }
        set {
            this.addField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddTypeRefinableSelectorElement))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public partial class AddTypeSelectorElement : TypeFilterSelectorElement {
    
    private bool skipVirtualMethodsField;
    
    private bool skipVirtualMethodsFieldSpecified;
    
    private bool skipVirtualIndexersField;
    
    private bool skipVirtualIndexersFieldSpecified;
    
    private string targetNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool SkipVirtualMethods {
        get {
            return this.skipVirtualMethodsField;
        }
        set {
            this.skipVirtualMethodsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SkipVirtualMethodsSpecified {
        get {
            return this.skipVirtualMethodsFieldSpecified;
        }
        set {
            this.skipVirtualMethodsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool SkipVirtualIndexers {
        get {
            return this.skipVirtualIndexersField;
        }
        set {
            this.skipVirtualIndexersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SkipVirtualIndexersSpecified {
        get {
            return this.skipVirtualIndexersFieldSpecified;
        }
        set {
            this.skipVirtualIndexersFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetName {
        get {
            return this.targetNameField;
        }
        set {
            this.targetNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public partial class AddTypeRefinableSelectorElement : AddTypeSelectorElement {
    
    private RemoveTypeSelectorElement[] removeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Remove")]
    public RemoveTypeSelectorElement[] Remove {
        get {
            return this.removeField;
        }
        set {
            this.removeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.danielrpotter.com/api/2017")]
public partial class ClearTypeSelectorElement : TypeSelectorElementBase {
}
